### ISSUE TITLE
master当前代码编译有错误

### ISSUE THREAD

**Issue by hongliangpan** [daxiongYang/renren-fast-vue#29]
错误截图
![image](https://user-images.githubusercontent.com/4516326/40645649-90a27646-6359-11e8-9881-538c825748b5.png)
日志文件
[2018-05-29T07_58_32_231Z-debug.log](https://github.com/daxiongYang/renren-fast-vue/files/2047268/2018-05-29T07_58_32_231Z-debug.log)

**Comment by daxiongYang** [comment]
你尝试使用`gulp default`命令，是否可行。

**Comment by hongliangpan** [comment]
\renren-fast-vue-master>gulp default

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Task function must be specified
    at Gulp.set [as _setTask] (G:\renren-fast-vue-master\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (G:\renren-fast-vue-master\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (G:\renren-fast-vue-master\gulpfile.js:27:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by hongliangpan** [comment]
https://www.jianshu.com/p/40b99bed3127
gulp4填坑 throw new assert.AssertionError

**Comment by hongliangpan** [comment]
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1784 packages from 845 contributors and audited 32915 packages in 240.607s
found 47 vulnerabilities (2 low, 36 moderate, 8 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by hongliangpan** [comment]
又部署一次，好了
今天没有执行
npm audit fix

**Comment by daxiongYang** [comment]
👏解决就好啦。你自己升级的gulp v4?
